### ISSUE TITLE
Make user profiles not useless

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/refresh-web#68]
- [ ] Show user's uploaded levels
- [ ] Recent photos
- [ ] Show first place ranks (depends on https://github.com/LittleBigRefresh/Refresh/issues/45)
- [ ] Comments
- [ ] User's recent reviews on levels (depends on https://github.com/LittleBigRefresh/Refresh/issues/82)
- [ ] Show platforms & games user has connected with (depends on https://github.com/LittleBigRefresh/Refresh/issues/244)
- [ ] Estimate of total play time (depends on https://github.com/LittleBigRefresh/Refresh/issues/144)
